vim.api.nvim_create_user_command('BookmarkletUnescape', function()
  local lines = vim.api.nvim_buf_get_lines(0, -2, -1, false)
  local nlines = vim.tbl_map(function(item)
    return item:gsub([[%%(%x%x)]], function(arg)
      return string.format('%c', tonumber(arg, 16))
    end)
  end, lines)
  vim.api.nvim_buf_set_lines(0, -2, -1, false, nlines)
end, { nargs = 0 })
